categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧹 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
template: |
  ## Changes
  
  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
  
  ## Docker
  
  - `docker pull systemli/ticker:$RESOLVED_VERSION`
