site_name: Systemli Ticker
site_author: Systemli Admin Team
repo_url: https://github.com/systemli/ticker

nav:
  - Home: index.md
  - Configuration: configuration.md
  - API: api.md
  - Migration: migration.md
  - Quick Install Guide: quick-install.md

theme:
  name: material

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - search
  - render_swagger

extra:
  generator: false
  social:
    - icon: fontawesome/solid/globe
      link: https://www.systemli.org
    - icon: fontawesome/brands/github
      link: https://github.com/systemli

markdown_extensions:
  - admonition
  - pymdownx.betterem
