// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockUploadStore creates a new instance of MockUploadStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUploadStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUploadStore {
	mock := &MockUploadStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUploadStore is an autogenerated mock type for the UploadStore type
type MockUploadStore struct {
	mock.Mock
}

type MockUploadStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUploadStore) EXPECT() *MockUploadStore_Expecter {
	return &MockUploadStore_Expecter{mock: &_m.Mock}
}

// DeleteUpload provides a mock function for the type MockUploadStore
func (_mock *MockUploadStore) DeleteUpload(upload Upload) error {
	ret := _mock.Called(upload)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Upload) error); ok {
		r0 = returnFunc(upload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUploadStore_DeleteUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUpload'
type MockUploadStore_DeleteUpload_Call struct {
	*mock.Call
}

// DeleteUpload is a helper method to define mock.On call
//   - upload Upload
func (_e *MockUploadStore_Expecter) DeleteUpload(upload interface{}) *MockUploadStore_DeleteUpload_Call {
	return &MockUploadStore_DeleteUpload_Call{Call: _e.mock.On("DeleteUpload", upload)}
}

func (_c *MockUploadStore_DeleteUpload_Call) Run(run func(upload Upload)) *MockUploadStore_DeleteUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Upload
		if args[0] != nil {
			arg0 = args[0].(Upload)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUploadStore_DeleteUpload_Call) Return(err error) *MockUploadStore_DeleteUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUploadStore_DeleteUpload_Call) RunAndReturn(run func(upload Upload) error) *MockUploadStore_DeleteUpload_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUploads provides a mock function for the type MockUploadStore
func (_mock *MockUploadStore) DeleteUploads(uploads []Upload) {
	_mock.Called(uploads)
	return
}

// MockUploadStore_DeleteUploads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUploads'
type MockUploadStore_DeleteUploads_Call struct {
	*mock.Call
}

// DeleteUploads is a helper method to define mock.On call
//   - uploads []Upload
func (_e *MockUploadStore_Expecter) DeleteUploads(uploads interface{}) *MockUploadStore_DeleteUploads_Call {
	return &MockUploadStore_DeleteUploads_Call{Call: _e.mock.On("DeleteUploads", uploads)}
}

func (_c *MockUploadStore_DeleteUploads_Call) Run(run func(uploads []Upload)) *MockUploadStore_DeleteUploads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []Upload
		if args[0] != nil {
			arg0 = args[0].([]Upload)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUploadStore_DeleteUploads_Call) Return() *MockUploadStore_DeleteUploads_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUploadStore_DeleteUploads_Call) RunAndReturn(run func(uploads []Upload)) *MockUploadStore_DeleteUploads_Call {
	_c.Run(run)
	return _c
}

// DeleteUploadsByTicker provides a mock function for the type MockUploadStore
func (_mock *MockUploadStore) DeleteUploadsByTicker(ticker *Ticker) error {
	ret := _mock.Called(ticker)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUploadsByTicker")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Ticker) error); ok {
		r0 = returnFunc(ticker)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUploadStore_DeleteUploadsByTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUploadsByTicker'
type MockUploadStore_DeleteUploadsByTicker_Call struct {
	*mock.Call
}

// DeleteUploadsByTicker is a helper method to define mock.On call
//   - ticker *Ticker
func (_e *MockUploadStore_Expecter) DeleteUploadsByTicker(ticker interface{}) *MockUploadStore_DeleteUploadsByTicker_Call {
	return &MockUploadStore_DeleteUploadsByTicker_Call{Call: _e.mock.On("DeleteUploadsByTicker", ticker)}
}

func (_c *MockUploadStore_DeleteUploadsByTicker_Call) Run(run func(ticker *Ticker)) *MockUploadStore_DeleteUploadsByTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Ticker
		if args[0] != nil {
			arg0 = args[0].(*Ticker)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUploadStore_DeleteUploadsByTicker_Call) Return(err error) *MockUploadStore_DeleteUploadsByTicker_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUploadStore_DeleteUploadsByTicker_Call) RunAndReturn(run func(ticker *Ticker) error) *MockUploadStore_DeleteUploadsByTicker_Call {
	_c.Call.Return(run)
	return _c
}

// FindUploadByUUID provides a mock function for the type MockUploadStore
func (_mock *MockUploadStore) FindUploadByUUID(uuid string) (Upload, error) {
	ret := _mock.Called(uuid)

	if len(ret) == 0 {
		panic("no return value specified for FindUploadByUUID")
	}

	var r0 Upload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (Upload, error)); ok {
		return returnFunc(uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Upload); ok {
		r0 = returnFunc(uuid)
	} else {
		r0 = ret.Get(0).(Upload)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadStore_FindUploadByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUploadByUUID'
type MockUploadStore_FindUploadByUUID_Call struct {
	*mock.Call
}

// FindUploadByUUID is a helper method to define mock.On call
//   - uuid string
func (_e *MockUploadStore_Expecter) FindUploadByUUID(uuid interface{}) *MockUploadStore_FindUploadByUUID_Call {
	return &MockUploadStore_FindUploadByUUID_Call{Call: _e.mock.On("FindUploadByUUID", uuid)}
}

func (_c *MockUploadStore_FindUploadByUUID_Call) Run(run func(uuid string)) *MockUploadStore_FindUploadByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUploadStore_FindUploadByUUID_Call) Return(upload Upload, err error) *MockUploadStore_FindUploadByUUID_Call {
	_c.Call.Return(upload, err)
	return _c
}

func (_c *MockUploadStore_FindUploadByUUID_Call) RunAndReturn(run func(uuid string) (Upload, error)) *MockUploadStore_FindUploadByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUploadsByIDs provides a mock function for the type MockUploadStore
func (_mock *MockUploadStore) FindUploadsByIDs(ids []int) ([]Upload, error) {
	ret := _mock.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for FindUploadsByIDs")
	}

	var r0 []Upload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int) ([]Upload, error)); ok {
		return returnFunc(ids)
	}
	if returnFunc, ok := ret.Get(0).(func([]int) []Upload); ok {
		r0 = returnFunc(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Upload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]int) error); ok {
		r1 = returnFunc(ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadStore_FindUploadsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUploadsByIDs'
type MockUploadStore_FindUploadsByIDs_Call struct {
	*mock.Call
}

// FindUploadsByIDs is a helper method to define mock.On call
//   - ids []int
func (_e *MockUploadStore_Expecter) FindUploadsByIDs(ids interface{}) *MockUploadStore_FindUploadsByIDs_Call {
	return &MockUploadStore_FindUploadsByIDs_Call{Call: _e.mock.On("FindUploadsByIDs", ids)}
}

func (_c *MockUploadStore_FindUploadsByIDs_Call) Run(run func(ids []int)) *MockUploadStore_FindUploadsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int
		if args[0] != nil {
			arg0 = args[0].([]int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUploadStore_FindUploadsByIDs_Call) Return(uploads []Upload, err error) *MockUploadStore_FindUploadsByIDs_Call {
	_c.Call.Return(uploads, err)
	return _c
}

func (_c *MockUploadStore_FindUploadsByIDs_Call) RunAndReturn(run func(ids []int) ([]Upload, error)) *MockUploadStore_FindUploadsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUpload provides a mock function for the type MockUploadStore
func (_mock *MockUploadStore) SaveUpload(upload *Upload) error {
	ret := _mock.Called(upload)

	if len(ret) == 0 {
		panic("no return value specified for SaveUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Upload) error); ok {
		r0 = returnFunc(upload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUploadStore_SaveUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUpload'
type MockUploadStore_SaveUpload_Call struct {
	*mock.Call
}

// SaveUpload is a helper method to define mock.On call
//   - upload *Upload
func (_e *MockUploadStore_Expecter) SaveUpload(upload interface{}) *MockUploadStore_SaveUpload_Call {
	return &MockUploadStore_SaveUpload_Call{Call: _e.mock.On("SaveUpload", upload)}
}

func (_c *MockUploadStore_SaveUpload_Call) Run(run func(upload *Upload)) *MockUploadStore_SaveUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Upload
		if args[0] != nil {
			arg0 = args[0].(*Upload)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUploadStore_SaveUpload_Call) Return(err error) *MockUploadStore_SaveUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUploadStore_SaveUpload_Call) RunAndReturn(run func(upload *Upload) error) *MockUploadStore_SaveUpload_Call {
	_c.Call.Return(run)
	return _c
}

// UploadPath provides a mock function for the type MockUploadStore
func (_mock *MockUploadStore) UploadPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UploadPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUploadStore_UploadPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadPath'
type MockUploadStore_UploadPath_Call struct {
	*mock.Call
}

// UploadPath is a helper method to define mock.On call
func (_e *MockUploadStore_Expecter) UploadPath() *MockUploadStore_UploadPath_Call {
	return &MockUploadStore_UploadPath_Call{Call: _e.mock.On("UploadPath")}
}

func (_c *MockUploadStore_UploadPath_Call) Run(run func()) *MockUploadStore_UploadPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUploadStore_UploadPath_Call) Return(s string) *MockUploadStore_UploadPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUploadStore_UploadPath_Call) RunAndReturn(run func() string) *MockUploadStore_UploadPath_Call {
	_c.Call.Return(run)
	return _c
}
