// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewMockUserStore creates a new instance of MockUserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserStore {
	mock := &MockUserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserStore is an autogenerated mock type for the UserStore type
type MockUserStore struct {
	mock.Mock
}

type MockUserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserStore) EXPECT() *MockUserStore_Expecter {
	return &MockUserStore_Expecter{mock: &_m.Mock}
}

// DeleteUser provides a mock function for the type MockUserStore
func (_mock *MockUserStore) DeleteUser(user User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserStore_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserStore_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - user User
func (_e *MockUserStore_Expecter) DeleteUser(user interface{}) *MockUserStore_DeleteUser_Call {
	return &MockUserStore_DeleteUser_Call{Call: _e.mock.On("DeleteUser", user)}
}

func (_c *MockUserStore_DeleteUser_Call) Run(run func(user User)) *MockUserStore_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 User
		if args[0] != nil {
			arg0 = args[0].(User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserStore_DeleteUser_Call) Return(err error) *MockUserStore_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserStore_DeleteUser_Call) RunAndReturn(run func(user User) error) *MockUserStore_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByEmail provides a mock function for the type MockUserStore
func (_mock *MockUserStore) FindUserByEmail(email string, opts ...QueryOpt) (User, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(email, opts)
	} else {
		tmpRet = _mock.Called(email)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...QueryOpt) (User, error)); ok {
		return returnFunc(email, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...QueryOpt) User); ok {
		r0 = returnFunc(email, opts...)
	} else {
		r0 = ret.Get(0).(User)
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...QueryOpt) error); ok {
		r1 = returnFunc(email, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStore_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type MockUserStore_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - email string
//   - opts ...QueryOpt
func (_e *MockUserStore_Expecter) FindUserByEmail(email interface{}, opts ...interface{}) *MockUserStore_FindUserByEmail_Call {
	return &MockUserStore_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail",
		append([]interface{}{email}, opts...)...)}
}

func (_c *MockUserStore_FindUserByEmail_Call) Run(run func(email string, opts ...QueryOpt)) *MockUserStore_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []QueryOpt
		var variadicArgs []QueryOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]QueryOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockUserStore_FindUserByEmail_Call) Return(user User, err error) *MockUserStore_FindUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserStore_FindUserByEmail_Call) RunAndReturn(run func(email string, opts ...QueryOpt) (User, error)) *MockUserStore_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByID provides a mock function for the type MockUserStore
func (_mock *MockUserStore) FindUserByID(id int, opts ...QueryOpt) (User, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(id, opts)
	} else {
		tmpRet = _mock.Called(id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, ...QueryOpt) (User, error)); ok {
		return returnFunc(id, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(int, ...QueryOpt) User); ok {
		r0 = returnFunc(id, opts...)
	} else {
		r0 = ret.Get(0).(User)
	}
	if returnFunc, ok := ret.Get(1).(func(int, ...QueryOpt) error); ok {
		r1 = returnFunc(id, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStore_FindUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByID'
type MockUserStore_FindUserByID_Call struct {
	*mock.Call
}

// FindUserByID is a helper method to define mock.On call
//   - id int
//   - opts ...QueryOpt
func (_e *MockUserStore_Expecter) FindUserByID(id interface{}, opts ...interface{}) *MockUserStore_FindUserByID_Call {
	return &MockUserStore_FindUserByID_Call{Call: _e.mock.On("FindUserByID",
		append([]interface{}{id}, opts...)...)}
}

func (_c *MockUserStore_FindUserByID_Call) Run(run func(id int, opts ...QueryOpt)) *MockUserStore_FindUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 []QueryOpt
		var variadicArgs []QueryOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]QueryOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockUserStore_FindUserByID_Call) Return(user User, err error) *MockUserStore_FindUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserStore_FindUserByID_Call) RunAndReturn(run func(id int, opts ...QueryOpt) (User, error)) *MockUserStore_FindUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUsers provides a mock function for the type MockUserStore
func (_mock *MockUserStore) FindUsers(filter UserFilter, opts ...QueryOpt) ([]User, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(filter, opts)
	} else {
		tmpRet = _mock.Called(filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindUsers")
	}

	var r0 []User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(UserFilter, ...QueryOpt) ([]User, error)); ok {
		return returnFunc(filter, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(UserFilter, ...QueryOpt) []User); ok {
		r0 = returnFunc(filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(UserFilter, ...QueryOpt) error); ok {
		r1 = returnFunc(filter, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStore_FindUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUsers'
type MockUserStore_FindUsers_Call struct {
	*mock.Call
}

// FindUsers is a helper method to define mock.On call
//   - filter UserFilter
//   - opts ...QueryOpt
func (_e *MockUserStore_Expecter) FindUsers(filter interface{}, opts ...interface{}) *MockUserStore_FindUsers_Call {
	return &MockUserStore_FindUsers_Call{Call: _e.mock.On("FindUsers",
		append([]interface{}{filter}, opts...)...)}
}

func (_c *MockUserStore_FindUsers_Call) Run(run func(filter UserFilter, opts ...QueryOpt)) *MockUserStore_FindUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 UserFilter
		if args[0] != nil {
			arg0 = args[0].(UserFilter)
		}
		var arg1 []QueryOpt
		var variadicArgs []QueryOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]QueryOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockUserStore_FindUsers_Call) Return(users []User, err error) *MockUserStore_FindUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserStore_FindUsers_Call) RunAndReturn(run func(filter UserFilter, opts ...QueryOpt) ([]User, error)) *MockUserStore_FindUsers_Call {
	_c.Call.Return(run)
	return _c
}

// FindUsersByIDs provides a mock function for the type MockUserStore
func (_mock *MockUserStore) FindUsersByIDs(ids []int, opts ...QueryOpt) ([]User, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ids, opts)
	} else {
		tmpRet = _mock.Called(ids)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindUsersByIDs")
	}

	var r0 []User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int, ...QueryOpt) ([]User, error)); ok {
		return returnFunc(ids, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func([]int, ...QueryOpt) []User); ok {
		r0 = returnFunc(ids, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]int, ...QueryOpt) error); ok {
		r1 = returnFunc(ids, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStore_FindUsersByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUsersByIDs'
type MockUserStore_FindUsersByIDs_Call struct {
	*mock.Call
}

// FindUsersByIDs is a helper method to define mock.On call
//   - ids []int
//   - opts ...QueryOpt
func (_e *MockUserStore_Expecter) FindUsersByIDs(ids interface{}, opts ...interface{}) *MockUserStore_FindUsersByIDs_Call {
	return &MockUserStore_FindUsersByIDs_Call{Call: _e.mock.On("FindUsersByIDs",
		append([]interface{}{ids}, opts...)...)}
}

func (_c *MockUserStore_FindUsersByIDs_Call) Run(run func(ids []int, opts ...QueryOpt)) *MockUserStore_FindUsersByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int
		if args[0] != nil {
			arg0 = args[0].([]int)
		}
		var arg1 []QueryOpt
		var variadicArgs []QueryOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]QueryOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockUserStore_FindUsersByIDs_Call) Return(users []User, err error) *MockUserStore_FindUsersByIDs_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserStore_FindUsersByIDs_Call) RunAndReturn(run func(ids []int, opts ...QueryOpt) ([]User, error)) *MockUserStore_FindUsersByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUser provides a mock function for the type MockUserStore
func (_mock *MockUserStore) SaveUser(user *User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserStore_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type MockUserStore_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - user *User
func (_e *MockUserStore_Expecter) SaveUser(user interface{}) *MockUserStore_SaveUser_Call {
	return &MockUserStore_SaveUser_Call{Call: _e.mock.On("SaveUser", user)}
}

func (_c *MockUserStore_SaveUser_Call) Run(run func(user *User)) *MockUserStore_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *User
		if args[0] != nil {
			arg0 = args[0].(*User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserStore_SaveUser_Call) Return(err error) *MockUserStore_SaveUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserStore_SaveUser_Call) RunAndReturn(run func(user *User) error) *MockUserStore_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}

// WithUserTx provides a mock function for the type MockUserStore
func (_mock *MockUserStore) WithUserTx(tx *gorm.DB) UserStore {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithUserTx")
	}

	var r0 UserStore
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) UserStore); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(UserStore)
		}
	}
	return r0
}

// MockUserStore_WithUserTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithUserTx'
type MockUserStore_WithUserTx_Call struct {
	*mock.Call
}

// WithUserTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockUserStore_Expecter) WithUserTx(tx interface{}) *MockUserStore_WithUserTx_Call {
	return &MockUserStore_WithUserTx_Call{Call: _e.mock.On("WithUserTx", tx)}
}

func (_c *MockUserStore_WithUserTx_Call) Run(run func(tx *gorm.DB)) *MockUserStore_WithUserTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserStore_WithUserTx_Call) Return(userStore UserStore) *MockUserStore_WithUserTx_Call {
	_c.Call.Return(userStore)
	return _c
}

func (_c *MockUserStore_WithUserTx_Call) RunAndReturn(run func(tx *gorm.DB) UserStore) *MockUserStore_WithUserTx_Call {
	_c.Call.Return(run)
	return _c
}
