// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTickerStore creates a new instance of MockTickerStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTickerStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTickerStore {
	mock := &MockTickerStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTickerStore is an autogenerated mock type for the TickerStore type
type MockTickerStore struct {
	mock.Mock
}

type MockTickerStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTickerStore) EXPECT() *MockTickerStore_Expecter {
	return &MockTickerStore_Expecter{mock: &_m.Mock}
}

// AddTickerUser provides a mock function for the type MockTickerStore
func (_mock *MockTickerStore) AddTickerUser(ticker *Ticker, user *User) error {
	ret := _mock.Called(ticker, user)

	if len(ret) == 0 {
		panic("no return value specified for AddTickerUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Ticker, *User) error); ok {
		r0 = returnFunc(ticker, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTickerStore_AddTickerUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTickerUser'
type MockTickerStore_AddTickerUser_Call struct {
	*mock.Call
}

// AddTickerUser is a helper method to define mock.On call
//   - ticker *Ticker
//   - user *User
func (_e *MockTickerStore_Expecter) AddTickerUser(ticker interface{}, user interface{}) *MockTickerStore_AddTickerUser_Call {
	return &MockTickerStore_AddTickerUser_Call{Call: _e.mock.On("AddTickerUser", ticker, user)}
}

func (_c *MockTickerStore_AddTickerUser_Call) Run(run func(ticker *Ticker, user *User)) *MockTickerStore_AddTickerUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Ticker
		if args[0] != nil {
			arg0 = args[0].(*Ticker)
		}
		var arg1 *User
		if args[1] != nil {
			arg1 = args[1].(*User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTickerStore_AddTickerUser_Call) Return(err error) *MockTickerStore_AddTickerUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTickerStore_AddTickerUser_Call) RunAndReturn(run func(ticker *Ticker, user *User) error) *MockTickerStore_AddTickerUser_Call {
	_c.Call.Return(run)
	return _c
}

// ClearIntegration provides a mock function for the type MockTickerStore
func (_mock *MockTickerStore) ClearIntegration(ticker *Ticker, integration Integration) error {
	ret := _mock.Called(ticker, integration)

	if len(ret) == 0 {
		panic("no return value specified for ClearIntegration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Ticker, Integration) error); ok {
		r0 = returnFunc(ticker, integration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTickerStore_ClearIntegration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearIntegration'
type MockTickerStore_ClearIntegration_Call struct {
	*mock.Call
}

// ClearIntegration is a helper method to define mock.On call
//   - ticker *Ticker
//   - integration Integration
func (_e *MockTickerStore_Expecter) ClearIntegration(ticker interface{}, integration interface{}) *MockTickerStore_ClearIntegration_Call {
	return &MockTickerStore_ClearIntegration_Call{Call: _e.mock.On("ClearIntegration", ticker, integration)}
}

func (_c *MockTickerStore_ClearIntegration_Call) Run(run func(ticker *Ticker, integration Integration)) *MockTickerStore_ClearIntegration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Ticker
		if args[0] != nil {
			arg0 = args[0].(*Ticker)
		}
		var arg1 Integration
		if args[1] != nil {
			arg1 = args[1].(Integration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTickerStore_ClearIntegration_Call) Return(err error) *MockTickerStore_ClearIntegration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTickerStore_ClearIntegration_Call) RunAndReturn(run func(ticker *Ticker, integration Integration) error) *MockTickerStore_ClearIntegration_Call {
	_c.Call.Return(run)
	return _c
}

// ClearIntegrations provides a mock function for the type MockTickerStore
func (_mock *MockTickerStore) ClearIntegrations(ticker *Ticker) error {
	ret := _mock.Called(ticker)

	if len(ret) == 0 {
		panic("no return value specified for ClearIntegrations")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Ticker) error); ok {
		r0 = returnFunc(ticker)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTickerStore_ClearIntegrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearIntegrations'
type MockTickerStore_ClearIntegrations_Call struct {
	*mock.Call
}

// ClearIntegrations is a helper method to define mock.On call
//   - ticker *Ticker
func (_e *MockTickerStore_Expecter) ClearIntegrations(ticker interface{}) *MockTickerStore_ClearIntegrations_Call {
	return &MockTickerStore_ClearIntegrations_Call{Call: _e.mock.On("ClearIntegrations", ticker)}
}

func (_c *MockTickerStore_ClearIntegrations_Call) Run(run func(ticker *Ticker)) *MockTickerStore_ClearIntegrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Ticker
		if args[0] != nil {
			arg0 = args[0].(*Ticker)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTickerStore_ClearIntegrations_Call) Return(err error) *MockTickerStore_ClearIntegrations_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTickerStore_ClearIntegrations_Call) RunAndReturn(run func(ticker *Ticker) error) *MockTickerStore_ClearIntegrations_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTicker provides a mock function for the type MockTickerStore
func (_mock *MockTickerStore) DeleteTicker(ticker *Ticker) error {
	ret := _mock.Called(ticker)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTicker")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Ticker) error); ok {
		r0 = returnFunc(ticker)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTickerStore_DeleteTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTicker'
type MockTickerStore_DeleteTicker_Call struct {
	*mock.Call
}

// DeleteTicker is a helper method to define mock.On call
//   - ticker *Ticker
func (_e *MockTickerStore_Expecter) DeleteTicker(ticker interface{}) *MockTickerStore_DeleteTicker_Call {
	return &MockTickerStore_DeleteTicker_Call{Call: _e.mock.On("DeleteTicker", ticker)}
}

func (_c *MockTickerStore_DeleteTicker_Call) Run(run func(ticker *Ticker)) *MockTickerStore_DeleteTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Ticker
		if args[0] != nil {
			arg0 = args[0].(*Ticker)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTickerStore_DeleteTicker_Call) Return(err error) *MockTickerStore_DeleteTicker_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTickerStore_DeleteTicker_Call) RunAndReturn(run func(ticker *Ticker) error) *MockTickerStore_DeleteTicker_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTickerUser provides a mock function for the type MockTickerStore
func (_mock *MockTickerStore) DeleteTickerUser(ticker *Ticker, user *User) error {
	ret := _mock.Called(ticker, user)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTickerUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Ticker, *User) error); ok {
		r0 = returnFunc(ticker, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTickerStore_DeleteTickerUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTickerUser'
type MockTickerStore_DeleteTickerUser_Call struct {
	*mock.Call
}

// DeleteTickerUser is a helper method to define mock.On call
//   - ticker *Ticker
//   - user *User
func (_e *MockTickerStore_Expecter) DeleteTickerUser(ticker interface{}, user interface{}) *MockTickerStore_DeleteTickerUser_Call {
	return &MockTickerStore_DeleteTickerUser_Call{Call: _e.mock.On("DeleteTickerUser", ticker, user)}
}

func (_c *MockTickerStore_DeleteTickerUser_Call) Run(run func(ticker *Ticker, user *User)) *MockTickerStore_DeleteTickerUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Ticker
		if args[0] != nil {
			arg0 = args[0].(*Ticker)
		}
		var arg1 *User
		if args[1] != nil {
			arg1 = args[1].(*User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTickerStore_DeleteTickerUser_Call) Return(err error) *MockTickerStore_DeleteTickerUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTickerStore_DeleteTickerUser_Call) RunAndReturn(run func(ticker *Ticker, user *User) error) *MockTickerStore_DeleteTickerUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTickerUsers provides a mock function for the type MockTickerStore
func (_mock *MockTickerStore) DeleteTickerUsers(ticker *Ticker) error {
	ret := _mock.Called(ticker)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTickerUsers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Ticker) error); ok {
		r0 = returnFunc(ticker)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTickerStore_DeleteTickerUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTickerUsers'
type MockTickerStore_DeleteTickerUsers_Call struct {
	*mock.Call
}

// DeleteTickerUsers is a helper method to define mock.On call
//   - ticker *Ticker
func (_e *MockTickerStore_Expecter) DeleteTickerUsers(ticker interface{}) *MockTickerStore_DeleteTickerUsers_Call {
	return &MockTickerStore_DeleteTickerUsers_Call{Call: _e.mock.On("DeleteTickerUsers", ticker)}
}

func (_c *MockTickerStore_DeleteTickerUsers_Call) Run(run func(ticker *Ticker)) *MockTickerStore_DeleteTickerUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Ticker
		if args[0] != nil {
			arg0 = args[0].(*Ticker)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTickerStore_DeleteTickerUsers_Call) Return(err error) *MockTickerStore_DeleteTickerUsers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTickerStore_DeleteTickerUsers_Call) RunAndReturn(run func(ticker *Ticker) error) *MockTickerStore_DeleteTickerUsers_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTickerWebsites provides a mock function for the type MockTickerStore
func (_mock *MockTickerStore) DeleteTickerWebsites(ticker *Ticker) error {
	ret := _mock.Called(ticker)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTickerWebsites")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Ticker) error); ok {
		r0 = returnFunc(ticker)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTickerStore_DeleteTickerWebsites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTickerWebsites'
type MockTickerStore_DeleteTickerWebsites_Call struct {
	*mock.Call
}

// DeleteTickerWebsites is a helper method to define mock.On call
//   - ticker *Ticker
func (_e *MockTickerStore_Expecter) DeleteTickerWebsites(ticker interface{}) *MockTickerStore_DeleteTickerWebsites_Call {
	return &MockTickerStore_DeleteTickerWebsites_Call{Call: _e.mock.On("DeleteTickerWebsites", ticker)}
}

func (_c *MockTickerStore_DeleteTickerWebsites_Call) Run(run func(ticker *Ticker)) *MockTickerStore_DeleteTickerWebsites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Ticker
		if args[0] != nil {
			arg0 = args[0].(*Ticker)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTickerStore_DeleteTickerWebsites_Call) Return(err error) *MockTickerStore_DeleteTickerWebsites_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTickerStore_DeleteTickerWebsites_Call) RunAndReturn(run func(ticker *Ticker) error) *MockTickerStore_DeleteTickerWebsites_Call {
	_c.Call.Return(run)
	return _c
}

// FindTickerByID provides a mock function for the type MockTickerStore
func (_mock *MockTickerStore) FindTickerByID(id int, opts ...QueryOpt) (Ticker, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(id, opts)
	} else {
		tmpRet = _mock.Called(id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindTickerByID")
	}

	var r0 Ticker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, ...QueryOpt) (Ticker, error)); ok {
		return returnFunc(id, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(int, ...QueryOpt) Ticker); ok {
		r0 = returnFunc(id, opts...)
	} else {
		r0 = ret.Get(0).(Ticker)
	}
	if returnFunc, ok := ret.Get(1).(func(int, ...QueryOpt) error); ok {
		r1 = returnFunc(id, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTickerStore_FindTickerByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTickerByID'
type MockTickerStore_FindTickerByID_Call struct {
	*mock.Call
}

// FindTickerByID is a helper method to define mock.On call
//   - id int
//   - opts ...QueryOpt
func (_e *MockTickerStore_Expecter) FindTickerByID(id interface{}, opts ...interface{}) *MockTickerStore_FindTickerByID_Call {
	return &MockTickerStore_FindTickerByID_Call{Call: _e.mock.On("FindTickerByID",
		append([]interface{}{id}, opts...)...)}
}

func (_c *MockTickerStore_FindTickerByID_Call) Run(run func(id int, opts ...QueryOpt)) *MockTickerStore_FindTickerByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 []QueryOpt
		var variadicArgs []QueryOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]QueryOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTickerStore_FindTickerByID_Call) Return(ticker Ticker, err error) *MockTickerStore_FindTickerByID_Call {
	_c.Call.Return(ticker, err)
	return _c
}

func (_c *MockTickerStore_FindTickerByID_Call) RunAndReturn(run func(id int, opts ...QueryOpt) (Ticker, error)) *MockTickerStore_FindTickerByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindTickerByOrigin provides a mock function for the type MockTickerStore
func (_mock *MockTickerStore) FindTickerByOrigin(origin string, opts ...QueryOpt) (Ticker, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(origin, opts)
	} else {
		tmpRet = _mock.Called(origin)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindTickerByOrigin")
	}

	var r0 Ticker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...QueryOpt) (Ticker, error)); ok {
		return returnFunc(origin, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...QueryOpt) Ticker); ok {
		r0 = returnFunc(origin, opts...)
	} else {
		r0 = ret.Get(0).(Ticker)
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...QueryOpt) error); ok {
		r1 = returnFunc(origin, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTickerStore_FindTickerByOrigin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTickerByOrigin'
type MockTickerStore_FindTickerByOrigin_Call struct {
	*mock.Call
}

// FindTickerByOrigin is a helper method to define mock.On call
//   - origin string
//   - opts ...QueryOpt
func (_e *MockTickerStore_Expecter) FindTickerByOrigin(origin interface{}, opts ...interface{}) *MockTickerStore_FindTickerByOrigin_Call {
	return &MockTickerStore_FindTickerByOrigin_Call{Call: _e.mock.On("FindTickerByOrigin",
		append([]interface{}{origin}, opts...)...)}
}

func (_c *MockTickerStore_FindTickerByOrigin_Call) Run(run func(origin string, opts ...QueryOpt)) *MockTickerStore_FindTickerByOrigin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []QueryOpt
		var variadicArgs []QueryOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]QueryOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTickerStore_FindTickerByOrigin_Call) Return(ticker Ticker, err error) *MockTickerStore_FindTickerByOrigin_Call {
	_c.Call.Return(ticker, err)
	return _c
}

func (_c *MockTickerStore_FindTickerByOrigin_Call) RunAndReturn(run func(origin string, opts ...QueryOpt) (Ticker, error)) *MockTickerStore_FindTickerByOrigin_Call {
	_c.Call.Return(run)
	return _c
}

// FindTickerByUserAndID provides a mock function for the type MockTickerStore
func (_mock *MockTickerStore) FindTickerByUserAndID(user User, id int, opts ...QueryOpt) (Ticker, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(user, id, opts)
	} else {
		tmpRet = _mock.Called(user, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindTickerByUserAndID")
	}

	var r0 Ticker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(User, int, ...QueryOpt) (Ticker, error)); ok {
		return returnFunc(user, id, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(User, int, ...QueryOpt) Ticker); ok {
		r0 = returnFunc(user, id, opts...)
	} else {
		r0 = ret.Get(0).(Ticker)
	}
	if returnFunc, ok := ret.Get(1).(func(User, int, ...QueryOpt) error); ok {
		r1 = returnFunc(user, id, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTickerStore_FindTickerByUserAndID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTickerByUserAndID'
type MockTickerStore_FindTickerByUserAndID_Call struct {
	*mock.Call
}

// FindTickerByUserAndID is a helper method to define mock.On call
//   - user User
//   - id int
//   - opts ...QueryOpt
func (_e *MockTickerStore_Expecter) FindTickerByUserAndID(user interface{}, id interface{}, opts ...interface{}) *MockTickerStore_FindTickerByUserAndID_Call {
	return &MockTickerStore_FindTickerByUserAndID_Call{Call: _e.mock.On("FindTickerByUserAndID",
		append([]interface{}{user, id}, opts...)...)}
}

func (_c *MockTickerStore_FindTickerByUserAndID_Call) Run(run func(user User, id int, opts ...QueryOpt)) *MockTickerStore_FindTickerByUserAndID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 User
		if args[0] != nil {
			arg0 = args[0].(User)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []QueryOpt
		var variadicArgs []QueryOpt
		if len(args) > 2 {
			variadicArgs = args[2].([]QueryOpt)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTickerStore_FindTickerByUserAndID_Call) Return(ticker Ticker, err error) *MockTickerStore_FindTickerByUserAndID_Call {
	_c.Call.Return(ticker, err)
	return _c
}

func (_c *MockTickerStore_FindTickerByUserAndID_Call) RunAndReturn(run func(user User, id int, opts ...QueryOpt) (Ticker, error)) *MockTickerStore_FindTickerByUserAndID_Call {
	_c.Call.Return(run)
	return _c
}

// FindTickersByIDs provides a mock function for the type MockTickerStore
func (_mock *MockTickerStore) FindTickersByIDs(ids []int, opts ...QueryOpt) ([]Ticker, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ids, opts)
	} else {
		tmpRet = _mock.Called(ids)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindTickersByIDs")
	}

	var r0 []Ticker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]int, ...QueryOpt) ([]Ticker, error)); ok {
		return returnFunc(ids, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func([]int, ...QueryOpt) []Ticker); ok {
		r0 = returnFunc(ids, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Ticker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]int, ...QueryOpt) error); ok {
		r1 = returnFunc(ids, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTickerStore_FindTickersByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTickersByIDs'
type MockTickerStore_FindTickersByIDs_Call struct {
	*mock.Call
}

// FindTickersByIDs is a helper method to define mock.On call
//   - ids []int
//   - opts ...QueryOpt
func (_e *MockTickerStore_Expecter) FindTickersByIDs(ids interface{}, opts ...interface{}) *MockTickerStore_FindTickersByIDs_Call {
	return &MockTickerStore_FindTickersByIDs_Call{Call: _e.mock.On("FindTickersByIDs",
		append([]interface{}{ids}, opts...)...)}
}

func (_c *MockTickerStore_FindTickersByIDs_Call) Run(run func(ids []int, opts ...QueryOpt)) *MockTickerStore_FindTickersByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []int
		if args[0] != nil {
			arg0 = args[0].([]int)
		}
		var arg1 []QueryOpt
		var variadicArgs []QueryOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]QueryOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTickerStore_FindTickersByIDs_Call) Return(tickers []Ticker, err error) *MockTickerStore_FindTickersByIDs_Call {
	_c.Call.Return(tickers, err)
	return _c
}

func (_c *MockTickerStore_FindTickersByIDs_Call) RunAndReturn(run func(ids []int, opts ...QueryOpt) ([]Ticker, error)) *MockTickerStore_FindTickersByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// FindTickersByUser provides a mock function for the type MockTickerStore
func (_mock *MockTickerStore) FindTickersByUser(user User, filter TickerFilter, opts ...QueryOpt) ([]Ticker, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(user, filter, opts)
	} else {
		tmpRet = _mock.Called(user, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindTickersByUser")
	}

	var r0 []Ticker
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(User, TickerFilter, ...QueryOpt) ([]Ticker, error)); ok {
		return returnFunc(user, filter, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(User, TickerFilter, ...QueryOpt) []Ticker); ok {
		r0 = returnFunc(user, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Ticker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(User, TickerFilter, ...QueryOpt) error); ok {
		r1 = returnFunc(user, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTickerStore_FindTickersByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTickersByUser'
type MockTickerStore_FindTickersByUser_Call struct {
	*mock.Call
}

// FindTickersByUser is a helper method to define mock.On call
//   - user User
//   - filter TickerFilter
//   - opts ...QueryOpt
func (_e *MockTickerStore_Expecter) FindTickersByUser(user interface{}, filter interface{}, opts ...interface{}) *MockTickerStore_FindTickersByUser_Call {
	return &MockTickerStore_FindTickersByUser_Call{Call: _e.mock.On("FindTickersByUser",
		append([]interface{}{user, filter}, opts...)...)}
}

func (_c *MockTickerStore_FindTickersByUser_Call) Run(run func(user User, filter TickerFilter, opts ...QueryOpt)) *MockTickerStore_FindTickersByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 User
		if args[0] != nil {
			arg0 = args[0].(User)
		}
		var arg1 TickerFilter
		if args[1] != nil {
			arg1 = args[1].(TickerFilter)
		}
		var arg2 []QueryOpt
		var variadicArgs []QueryOpt
		if len(args) > 2 {
			variadicArgs = args[2].([]QueryOpt)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTickerStore_FindTickersByUser_Call) Return(tickers []Ticker, err error) *MockTickerStore_FindTickersByUser_Call {
	_c.Call.Return(tickers, err)
	return _c
}

func (_c *MockTickerStore_FindTickersByUser_Call) RunAndReturn(run func(user User, filter TickerFilter, opts ...QueryOpt) ([]Ticker, error)) *MockTickerStore_FindTickersByUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindUsersByTicker provides a mock function for the type MockTickerStore
func (_mock *MockTickerStore) FindUsersByTicker(ticker Ticker, opts ...QueryOpt) ([]User, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ticker, opts)
	} else {
		tmpRet = _mock.Called(ticker)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindUsersByTicker")
	}

	var r0 []User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(Ticker, ...QueryOpt) ([]User, error)); ok {
		return returnFunc(ticker, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(Ticker, ...QueryOpt) []User); ok {
		r0 = returnFunc(ticker, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(Ticker, ...QueryOpt) error); ok {
		r1 = returnFunc(ticker, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTickerStore_FindUsersByTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUsersByTicker'
type MockTickerStore_FindUsersByTicker_Call struct {
	*mock.Call
}

// FindUsersByTicker is a helper method to define mock.On call
//   - ticker Ticker
//   - opts ...QueryOpt
func (_e *MockTickerStore_Expecter) FindUsersByTicker(ticker interface{}, opts ...interface{}) *MockTickerStore_FindUsersByTicker_Call {
	return &MockTickerStore_FindUsersByTicker_Call{Call: _e.mock.On("FindUsersByTicker",
		append([]interface{}{ticker}, opts...)...)}
}

func (_c *MockTickerStore_FindUsersByTicker_Call) Run(run func(ticker Ticker, opts ...QueryOpt)) *MockTickerStore_FindUsersByTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Ticker
		if args[0] != nil {
			arg0 = args[0].(Ticker)
		}
		var arg1 []QueryOpt
		var variadicArgs []QueryOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]QueryOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockTickerStore_FindUsersByTicker_Call) Return(users []User, err error) *MockTickerStore_FindUsersByTicker_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockTickerStore_FindUsersByTicker_Call) RunAndReturn(run func(ticker Ticker, opts ...QueryOpt) ([]User, error)) *MockTickerStore_FindUsersByTicker_Call {
	_c.Call.Return(run)
	return _c
}

// ResetTicker provides a mock function for the type MockTickerStore
func (_mock *MockTickerStore) ResetTicker(ticker *Ticker) error {
	ret := _mock.Called(ticker)

	if len(ret) == 0 {
		panic("no return value specified for ResetTicker")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Ticker) error); ok {
		r0 = returnFunc(ticker)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTickerStore_ResetTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetTicker'
type MockTickerStore_ResetTicker_Call struct {
	*mock.Call
}

// ResetTicker is a helper method to define mock.On call
//   - ticker *Ticker
func (_e *MockTickerStore_Expecter) ResetTicker(ticker interface{}) *MockTickerStore_ResetTicker_Call {
	return &MockTickerStore_ResetTicker_Call{Call: _e.mock.On("ResetTicker", ticker)}
}

func (_c *MockTickerStore_ResetTicker_Call) Run(run func(ticker *Ticker)) *MockTickerStore_ResetTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Ticker
		if args[0] != nil {
			arg0 = args[0].(*Ticker)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTickerStore_ResetTicker_Call) Return(err error) *MockTickerStore_ResetTicker_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTickerStore_ResetTicker_Call) RunAndReturn(run func(ticker *Ticker) error) *MockTickerStore_ResetTicker_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTicker provides a mock function for the type MockTickerStore
func (_mock *MockTickerStore) SaveTicker(ticker *Ticker) error {
	ret := _mock.Called(ticker)

	if len(ret) == 0 {
		panic("no return value specified for SaveTicker")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Ticker) error); ok {
		r0 = returnFunc(ticker)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTickerStore_SaveTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTicker'
type MockTickerStore_SaveTicker_Call struct {
	*mock.Call
}

// SaveTicker is a helper method to define mock.On call
//   - ticker *Ticker
func (_e *MockTickerStore_Expecter) SaveTicker(ticker interface{}) *MockTickerStore_SaveTicker_Call {
	return &MockTickerStore_SaveTicker_Call{Call: _e.mock.On("SaveTicker", ticker)}
}

func (_c *MockTickerStore_SaveTicker_Call) Run(run func(ticker *Ticker)) *MockTickerStore_SaveTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Ticker
		if args[0] != nil {
			arg0 = args[0].(*Ticker)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTickerStore_SaveTicker_Call) Return(err error) *MockTickerStore_SaveTicker_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTickerStore_SaveTicker_Call) RunAndReturn(run func(ticker *Ticker) error) *MockTickerStore_SaveTicker_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTickerWebsites provides a mock function for the type MockTickerStore
func (_mock *MockTickerStore) SaveTickerWebsites(ticker *Ticker, websites []TickerWebsite) error {
	ret := _mock.Called(ticker, websites)

	if len(ret) == 0 {
		panic("no return value specified for SaveTickerWebsites")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Ticker, []TickerWebsite) error); ok {
		r0 = returnFunc(ticker, websites)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTickerStore_SaveTickerWebsites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTickerWebsites'
type MockTickerStore_SaveTickerWebsites_Call struct {
	*mock.Call
}

// SaveTickerWebsites is a helper method to define mock.On call
//   - ticker *Ticker
//   - websites []TickerWebsite
func (_e *MockTickerStore_Expecter) SaveTickerWebsites(ticker interface{}, websites interface{}) *MockTickerStore_SaveTickerWebsites_Call {
	return &MockTickerStore_SaveTickerWebsites_Call{Call: _e.mock.On("SaveTickerWebsites", ticker, websites)}
}

func (_c *MockTickerStore_SaveTickerWebsites_Call) Run(run func(ticker *Ticker, websites []TickerWebsite)) *MockTickerStore_SaveTickerWebsites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Ticker
		if args[0] != nil {
			arg0 = args[0].(*Ticker)
		}
		var arg1 []TickerWebsite
		if args[1] != nil {
			arg1 = args[1].([]TickerWebsite)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTickerStore_SaveTickerWebsites_Call) Return(err error) *MockTickerStore_SaveTickerWebsites_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTickerStore_SaveTickerWebsites_Call) RunAndReturn(run func(ticker *Ticker, websites []TickerWebsite) error) *MockTickerStore_SaveTickerWebsites_Call {
	_c.Call.Return(run)
	return _c
}
