// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/systemli/ticker/internal/api/pagination"
	"gorm.io/gorm"
)

// NewMockMessageStore creates a new instance of MockMessageStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageStore {
	mock := &MockMessageStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageStore is an autogenerated mock type for the MessageStore type
type MockMessageStore struct {
	mock.Mock
}

type MockMessageStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageStore) EXPECT() *MockMessageStore_Expecter {
	return &MockMessageStore_Expecter{mock: &_m.Mock}
}

// DeleteMessage provides a mock function for the type MockMessageStore
func (_mock *MockMessageStore) DeleteMessage(message Message) error {
	ret := _mock.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Message) error); ok {
		r0 = returnFunc(message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageStore_DeleteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessage'
type MockMessageStore_DeleteMessage_Call struct {
	*mock.Call
}

// DeleteMessage is a helper method to define mock.On call
//   - message Message
func (_e *MockMessageStore_Expecter) DeleteMessage(message interface{}) *MockMessageStore_DeleteMessage_Call {
	return &MockMessageStore_DeleteMessage_Call{Call: _e.mock.On("DeleteMessage", message)}
}

func (_c *MockMessageStore_DeleteMessage_Call) Run(run func(message Message)) *MockMessageStore_DeleteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Message
		if args[0] != nil {
			arg0 = args[0].(Message)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessageStore_DeleteMessage_Call) Return(err error) *MockMessageStore_DeleteMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageStore_DeleteMessage_Call) RunAndReturn(run func(message Message) error) *MockMessageStore_DeleteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMessages provides a mock function for the type MockMessageStore
func (_mock *MockMessageStore) DeleteMessages(ticker *Ticker) error {
	ret := _mock.Called(ticker)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Ticker) error); ok {
		r0 = returnFunc(ticker)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageStore_DeleteMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessages'
type MockMessageStore_DeleteMessages_Call struct {
	*mock.Call
}

// DeleteMessages is a helper method to define mock.On call
//   - ticker *Ticker
func (_e *MockMessageStore_Expecter) DeleteMessages(ticker interface{}) *MockMessageStore_DeleteMessages_Call {
	return &MockMessageStore_DeleteMessages_Call{Call: _e.mock.On("DeleteMessages", ticker)}
}

func (_c *MockMessageStore_DeleteMessages_Call) Run(run func(ticker *Ticker)) *MockMessageStore_DeleteMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Ticker
		if args[0] != nil {
			arg0 = args[0].(*Ticker)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessageStore_DeleteMessages_Call) Return(err error) *MockMessageStore_DeleteMessages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageStore_DeleteMessages_Call) RunAndReturn(run func(ticker *Ticker) error) *MockMessageStore_DeleteMessages_Call {
	_c.Call.Return(run)
	return _c
}

// FindMessage provides a mock function for the type MockMessageStore
func (_mock *MockMessageStore) FindMessage(tickerID int, messageID int, opts ...QueryOpt) (Message, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(tickerID, messageID, opts)
	} else {
		tmpRet = _mock.Called(tickerID, messageID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindMessage")
	}

	var r0 Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int, ...QueryOpt) (Message, error)); ok {
		return returnFunc(tickerID, messageID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int, ...QueryOpt) Message); ok {
		r0 = returnFunc(tickerID, messageID, opts...)
	} else {
		r0 = ret.Get(0).(Message)
	}
	if returnFunc, ok := ret.Get(1).(func(int, int, ...QueryOpt) error); ok {
		r1 = returnFunc(tickerID, messageID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessageStore_FindMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMessage'
type MockMessageStore_FindMessage_Call struct {
	*mock.Call
}

// FindMessage is a helper method to define mock.On call
//   - tickerID int
//   - messageID int
//   - opts ...QueryOpt
func (_e *MockMessageStore_Expecter) FindMessage(tickerID interface{}, messageID interface{}, opts ...interface{}) *MockMessageStore_FindMessage_Call {
	return &MockMessageStore_FindMessage_Call{Call: _e.mock.On("FindMessage",
		append([]interface{}{tickerID, messageID}, opts...)...)}
}

func (_c *MockMessageStore_FindMessage_Call) Run(run func(tickerID int, messageID int, opts ...QueryOpt)) *MockMessageStore_FindMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []QueryOpt
		var variadicArgs []QueryOpt
		if len(args) > 2 {
			variadicArgs = args[2].([]QueryOpt)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMessageStore_FindMessage_Call) Return(message Message, err error) *MockMessageStore_FindMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockMessageStore_FindMessage_Call) RunAndReturn(run func(tickerID int, messageID int, opts ...QueryOpt) (Message, error)) *MockMessageStore_FindMessage_Call {
	_c.Call.Return(run)
	return _c
}

// FindMessagesByTicker provides a mock function for the type MockMessageStore
func (_mock *MockMessageStore) FindMessagesByTicker(ticker Ticker, opts ...QueryOpt) ([]Message, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ticker, opts)
	} else {
		tmpRet = _mock.Called(ticker)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindMessagesByTicker")
	}

	var r0 []Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(Ticker, ...QueryOpt) ([]Message, error)); ok {
		return returnFunc(ticker, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(Ticker, ...QueryOpt) []Message); ok {
		r0 = returnFunc(ticker, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(Ticker, ...QueryOpt) error); ok {
		r1 = returnFunc(ticker, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessageStore_FindMessagesByTicker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMessagesByTicker'
type MockMessageStore_FindMessagesByTicker_Call struct {
	*mock.Call
}

// FindMessagesByTicker is a helper method to define mock.On call
//   - ticker Ticker
//   - opts ...QueryOpt
func (_e *MockMessageStore_Expecter) FindMessagesByTicker(ticker interface{}, opts ...interface{}) *MockMessageStore_FindMessagesByTicker_Call {
	return &MockMessageStore_FindMessagesByTicker_Call{Call: _e.mock.On("FindMessagesByTicker",
		append([]interface{}{ticker}, opts...)...)}
}

func (_c *MockMessageStore_FindMessagesByTicker_Call) Run(run func(ticker Ticker, opts ...QueryOpt)) *MockMessageStore_FindMessagesByTicker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Ticker
		if args[0] != nil {
			arg0 = args[0].(Ticker)
		}
		var arg1 []QueryOpt
		var variadicArgs []QueryOpt
		if len(args) > 1 {
			variadicArgs = args[1].([]QueryOpt)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockMessageStore_FindMessagesByTicker_Call) Return(messages []Message, err error) *MockMessageStore_FindMessagesByTicker_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockMessageStore_FindMessagesByTicker_Call) RunAndReturn(run func(ticker Ticker, opts ...QueryOpt) ([]Message, error)) *MockMessageStore_FindMessagesByTicker_Call {
	_c.Call.Return(run)
	return _c
}

// FindMessagesByTickerAndPagination provides a mock function for the type MockMessageStore
func (_mock *MockMessageStore) FindMessagesByTickerAndPagination(ticker Ticker, p pagination.Pagination, opts ...QueryOpt) ([]Message, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ticker, p, opts)
	} else {
		tmpRet = _mock.Called(ticker, p)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindMessagesByTickerAndPagination")
	}

	var r0 []Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(Ticker, pagination.Pagination, ...QueryOpt) ([]Message, error)); ok {
		return returnFunc(ticker, p, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(Ticker, pagination.Pagination, ...QueryOpt) []Message); ok {
		r0 = returnFunc(ticker, p, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(Ticker, pagination.Pagination, ...QueryOpt) error); ok {
		r1 = returnFunc(ticker, p, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessageStore_FindMessagesByTickerAndPagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMessagesByTickerAndPagination'
type MockMessageStore_FindMessagesByTickerAndPagination_Call struct {
	*mock.Call
}

// FindMessagesByTickerAndPagination is a helper method to define mock.On call
//   - ticker Ticker
//   - p pagination.Pagination
//   - opts ...QueryOpt
func (_e *MockMessageStore_Expecter) FindMessagesByTickerAndPagination(ticker interface{}, p interface{}, opts ...interface{}) *MockMessageStore_FindMessagesByTickerAndPagination_Call {
	return &MockMessageStore_FindMessagesByTickerAndPagination_Call{Call: _e.mock.On("FindMessagesByTickerAndPagination",
		append([]interface{}{ticker, p}, opts...)...)}
}

func (_c *MockMessageStore_FindMessagesByTickerAndPagination_Call) Run(run func(ticker Ticker, p pagination.Pagination, opts ...QueryOpt)) *MockMessageStore_FindMessagesByTickerAndPagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Ticker
		if args[0] != nil {
			arg0 = args[0].(Ticker)
		}
		var arg1 pagination.Pagination
		if args[1] != nil {
			arg1 = args[1].(pagination.Pagination)
		}
		var arg2 []QueryOpt
		var variadicArgs []QueryOpt
		if len(args) > 2 {
			variadicArgs = args[2].([]QueryOpt)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMessageStore_FindMessagesByTickerAndPagination_Call) Return(messages []Message, err error) *MockMessageStore_FindMessagesByTickerAndPagination_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockMessageStore_FindMessagesByTickerAndPagination_Call) RunAndReturn(run func(ticker Ticker, p pagination.Pagination, opts ...QueryOpt) ([]Message, error)) *MockMessageStore_FindMessagesByTickerAndPagination_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMessage provides a mock function for the type MockMessageStore
func (_mock *MockMessageStore) SaveMessage(message *Message) error {
	ret := _mock.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for SaveMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Message) error); ok {
		r0 = returnFunc(message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageStore_SaveMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMessage'
type MockMessageStore_SaveMessage_Call struct {
	*mock.Call
}

// SaveMessage is a helper method to define mock.On call
//   - message *Message
func (_e *MockMessageStore_Expecter) SaveMessage(message interface{}) *MockMessageStore_SaveMessage_Call {
	return &MockMessageStore_SaveMessage_Call{Call: _e.mock.On("SaveMessage", message)}
}

func (_c *MockMessageStore_SaveMessage_Call) Run(run func(message *Message)) *MockMessageStore_SaveMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Message
		if args[0] != nil {
			arg0 = args[0].(*Message)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessageStore_SaveMessage_Call) Return(err error) *MockMessageStore_SaveMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageStore_SaveMessage_Call) RunAndReturn(run func(message *Message) error) *MockMessageStore_SaveMessage_Call {
	_c.Call.Return(run)
	return _c
}

// WithMessageTx provides a mock function for the type MockMessageStore
func (_mock *MockMessageStore) WithMessageTx(tx *gorm.DB) MessageStore {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithMessageTx")
	}

	var r0 MessageStore
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) MessageStore); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(MessageStore)
		}
	}
	return r0
}

// MockMessageStore_WithMessageTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithMessageTx'
type MockMessageStore_WithMessageTx_Call struct {
	*mock.Call
}

// WithMessageTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockMessageStore_Expecter) WithMessageTx(tx interface{}) *MockMessageStore_WithMessageTx_Call {
	return &MockMessageStore_WithMessageTx_Call{Call: _e.mock.On("WithMessageTx", tx)}
}

func (_c *MockMessageStore_WithMessageTx_Call) Run(run func(tx *gorm.DB)) *MockMessageStore_WithMessageTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessageStore_WithMessageTx_Call) Return(messageStore MessageStore) *MockMessageStore_WithMessageTx_Call {
	_c.Call.Return(messageStore)
	return _c
}

func (_c *MockMessageStore_WithMessageTx_Call) RunAndReturn(run func(tx *gorm.DB) MessageStore) *MockMessageStore_WithMessageTx_Call {
	_c.Call.Return(run)
	return _c
}
