// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSettingsStore creates a new instance of MockSettingsStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSettingsStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSettingsStore {
	mock := &MockSettingsStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSettingsStore is an autogenerated mock type for the SettingsStore type
type MockSettingsStore struct {
	mock.Mock
}

type MockSettingsStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSettingsStore) EXPECT() *MockSettingsStore_Expecter {
	return &MockSettingsStore_Expecter{mock: &_m.Mock}
}

// GetSetting provides a mock function for the type MockSettingsStore
func (_mock *MockSettingsStore) GetSetting(name string) (Setting, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetSetting")
	}

	var r0 Setting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (Setting, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Setting); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(Setting)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettingsStore_GetSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSetting'
type MockSettingsStore_GetSetting_Call struct {
	*mock.Call
}

// GetSetting is a helper method to define mock.On call
//   - name string
func (_e *MockSettingsStore_Expecter) GetSetting(name interface{}) *MockSettingsStore_GetSetting_Call {
	return &MockSettingsStore_GetSetting_Call{Call: _e.mock.On("GetSetting", name)}
}

func (_c *MockSettingsStore_GetSetting_Call) Run(run func(name string)) *MockSettingsStore_GetSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSettingsStore_GetSetting_Call) Return(setting Setting, err error) *MockSettingsStore_GetSetting_Call {
	_c.Call.Return(setting, err)
	return _c
}

func (_c *MockSettingsStore_GetSetting_Call) RunAndReturn(run func(name string) (Setting, error)) *MockSettingsStore_GetSetting_Call {
	_c.Call.Return(run)
	return _c
}

// SaveSetting provides a mock function for the type MockSettingsStore
func (_mock *MockSettingsStore) SaveSetting(setting *Setting) error {
	ret := _mock.Called(setting)

	if len(ret) == 0 {
		panic("no return value specified for SaveSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Setting) error); ok {
		r0 = returnFunc(setting)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSettingsStore_SaveSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSetting'
type MockSettingsStore_SaveSetting_Call struct {
	*mock.Call
}

// SaveSetting is a helper method to define mock.On call
//   - setting *Setting
func (_e *MockSettingsStore_Expecter) SaveSetting(setting interface{}) *MockSettingsStore_SaveSetting_Call {
	return &MockSettingsStore_SaveSetting_Call{Call: _e.mock.On("SaveSetting", setting)}
}

func (_c *MockSettingsStore_SaveSetting_Call) Run(run func(setting *Setting)) *MockSettingsStore_SaveSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Setting
		if args[0] != nil {
			arg0 = args[0].(*Setting)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSettingsStore_SaveSetting_Call) Return(err error) *MockSettingsStore_SaveSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSettingsStore_SaveSetting_Call) RunAndReturn(run func(setting *Setting) error) *MockSettingsStore_SaveSetting_Call {
	_c.Call.Return(run)
	return _c
}
