name: Integration

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - shell: bash
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive --depth=1
      - name: Setup go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.16.x'
      - name: Download dependencies
        run: go get -t -v ./...
      - name: Vet
        run: make vet
      - name: Test
        run: make coverage
      - name: Codecov
        uses: codecov/codecov-action@v2.0.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - shell: bash
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive --depth=1
      - name: Setup go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.16.x'
      - name: Download dependencies
        run: go get -t -v ./...
      - name: Build
        run: make build

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - shell: bash
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive --depth=1
      - name: Docker
        run: make docker
