name: Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Test
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-20.04
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Build
        run: go build

      - name: Docker
        run: docker build .

  automerge:
    name: Merge Automatically
    needs: [test, build]
    runs-on: ubuntu-20.04

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Obtain Access Token
        id: acces_token
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.SYSTEMLI_APP_CREDENTIALS_TOKEN }})"
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"

      - name: Merge
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ steps.acces_token.outputs.token }}
