name: Integration

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          submodules: 'recursive'

      - name: Setup go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.17.x'

      - name: Cache Go Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: make coverage

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-20.04
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          submodules: 'recursive'

      - name: Setup go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.17.x'

      - name: Cache Go Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: make build

  docker:
    name: Docker
    runs-on: ubuntu-20.04
    needs: [test, build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          submodules: 'recursive'

      - name: Docker
        run: make docker
