name: Documentation

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/mkdocs.yml'
      - 'mkdocs.yml'
      - 'docs/**'

jobs:
  mkdocs:
    name: Build & Deploy Documentation
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Deploy Documentation
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
